# Manga was here
name: Fetch PCBS data

on: [push]

jobs:
  run:
    name: Run Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: { ref: fetch-pcbs-action }

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: Install dependencies
        run: pip install beautifulsoup4 lxml

      - name: Run script
        run: python scripts/fetch_pcbs.py public/pcbs_data.json

      - name: Commit and push changes
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor}}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Update pcbs_data" && git push || echo "Nothing to commit"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
