name: Fetch PCBS data

on:
  schedule:
      - cron: '*/5 * * * *'
    # - cron: "0 23 * * *" # Run daily at midnight

jobs:
  run:
    name: Run Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: { ref: fetch-pcbs-action }

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 

      - name: Install dependencies
        run: pip install beautifulsoup4

      - name: Run script
        run: python scripts/fetch_pcbs.py public/pcbs_data.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/pcbs_data.json
          git commit -m "Update pcbs_data"
          git push
